### ISSUE TITLE
Invalidate cached image?

### ISSUE THREAD

**Issue by kbrmimbyl** [renefloor/flutter_cached_network_image#117]
Is there a way to force-invalidate a given cached image?

**Comment by wiradikusuma** [comment]
+1

**Comment by renefloor** [comment]
There is now.

**Comment by Xgamefactory** [comment]
> There is now.
how ?

**Comment by renefloor** [comment]
@Xgamefactory if you import flutter_cache_manager you can call `DefaultCacheManager().removeFile(String url)` or `DefaultCacheManager(). emptyCache()`

**Comment by jagmit** [comment]
@renefloor Thanks for this hint! Removing the entry from the cache with `DefaultCacheManager().removeFile()` and causing the CachedNetworkImage to rebuild does cause a new fetching of the image over network.

Prior to 3f598189d63a20668dc293c5e7ddd9cbbb8379a0 this might could have been fixed by additionally checking whether the CacheManager still got the file in memory.

```dart
  @override
  void didUpdateWidget(CachedNetworkImage oldWidget) {
    if (oldWidget.imageUrl != widget.imageUrl || _cacheManager.getFileFromMemory(imageUrl) == null) {
      _streamBuilderKey = UniqueKey();
      if (!widget.useOldImageOnUrlChange) {
        _disposeImageHolders();
        _imageHolders.clear();
      }
      _createFileStream();
    }
    super.didUpdateWidget(oldWidget);
  }
```

I don't know how to do this with the new `OctoImage` widget. Can you look into this?

**Comment by renefloor** [comment]
@jagmit 'evict' should work: https://api.flutter.dev/flutter/painting/ImageProvider/evict.html
So `await CachedNetworkImageProvider(url).evict()` after `DefaultCacheManager().removeFile()`.

**Comment by jagmit** [comment]
Thank you for your quick reply. Evicting the image from the ImageProvider still doesn't cause the image to refetch when rebuilding the widget after the cache eviction.
Maybe the [didUpdateWidget in OctoImage](https://github.com/Baseflow/octo_image/blob/8c33667cb5a7593651a1085edd299eb38d73be32/lib/src/image.dart#L310) is the problem here?

**Comment by renefloor** [comment]
Have to test that, but I at least see an issue there on this line: https://github.com/Baseflow/octo_image/blob/8c33667cb5a7593651a1085edd299eb38d73be32/lib/src/image.dart#L313

**Comment by jagmit** [comment]
Were you able to reproduce it or should I try to provide an example project with this issue?

**Comment by renefloor** [comment]
Didn't have time for it yet, but an example is always nice to speed things up.
