### ISSUE TITLE
The same picture, but the address is different each time it is loaded, can you add a cache ID?

### ISSUE THREAD

**Issue by gaojuanjuan** [renefloor/flutter_cached_network_image#175]
The same picture, but the address is different each time it is loaded, can you add a cache ID?

**Comment by nuc134r** [comment]
Would love it too.

**Comment by renefloor** [comment]
As you can see in the docs you can supply your own BaseCacheManager:
https://pub.dev/documentation/cached_network_image/latest/cached_network_image/CachedNetworkImage-class.html

You can make that one like the DefaultCacheManager, but supply a [FileFetcher](https://pub.dev/documentation/flutter_cache_manager/latest/flutter_cache_manager/FileFetcher.html) to determine which url to fetch for which key.

Then you just supply keys instead of urls to the image.
