### ISSUE TITLE
Failing to retrieve image from network should not throw an exception.

### ISSUE THREAD

**Issue by jeffmikels** [renefloor/flutter_cached_network_image#49]
I'm happy to submit a pull request, but this seems like an easy fix.

Having an error callback is good, but throwing an exception when a network image fails to load is too extreme.

**Comment by mattiagalati** [comment]
In my case, I'm quite comfortable that plugin throws an exception, due to the fact that I send all the exceptions to a remote service, and this let me deep inspect every exception.

That said, an unreachable url or a network error is not a blocking exception and using the CachedNetworkImage with the errorWidget argument, It's like telling "ok, I'm aware that the image can be unreachable, but if you cant download, inform user of a (ie) network problem" and I would like the plugin does not throw any exception, since this would duplicate the remote exception, alerting of an issue that is, in fact, already solved for me.

**Comment by rav3r** [comment]
@renefloor Any updates on that? I see that there is pending PR which will also resolve this issue:
https://github.com/renefloor/flutter_cached_network_image/pull/95
