### ISSUE TITLE
http version problem

### ISSUE THREAD

**Issue by UnCheon** [renefloor/flutter_cached_network_image#85]
Hi. When I get packages and get dependencies,  the error appears.

This is the logs.

Because every version of flutter_test from sdk depends on package_resolver 1.0.4 which depends on http ^0.11.0, every version of flutter_test from sdk requires http ^0.11.0.
And because cached_network_image >=0.5.0 depends on flutter_cache_manager ^0.2.0 which depends on http ^0.12.0, flutter_test from sdk is incompatible with cached_network_image >=0.5.0.
So, because passion_timer_scoped depends on both cached_network_image ^0.5.0 and flutter_test any from sdk, version solving failed.

pub get failed (1)

This is my flutter doctor result.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.12.6 16G1510, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.2)
[!] VS Code (version 1.28.1)
[✓] Connected devices (3 available)

! Doctor found issues in 2 categories.

How can I get dependencies ?

**Comment by renefloor** [comment]
Version 0.5.0 is published to make the library compatible with the latest version of flutter on the master branch. You should use 0.4.2 if you use an older version of Flutter.

**Comment by cyon1c** [comment]
This still seems to be an issue. With `cached_network_image: ^0.5.0` and `http: ^0.12.0`, I receive this issue:

`Because every version of flutter_test from sdk depends on http 0.11.3+17 and my_project depends on http ^0.12.0, flutter_test from sdk is forbidden. So, because my_project depends on flutter_test any from sdk, version solving failed.`

Meanwhile, with `cached_network_image: ^0.5.0` and `http: ^0.11.3+17`, I receive this:

`Because every version of flutter_test from sdk depends on http 0.11.3+17 and my_project depends on http ^0.12.0, flutter_test from sdk is forbidden. So, because my_project depends on flutter_test any from sdk, version solving failed.`

`flutter doctor` output:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio (version 3.2)
[!] VS Code (version 1.25.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by renefloor** [comment]
@cyon1c And version 0.4.2 doesn't work either for you?

**Comment by cyon1c** [comment]
0.4.2 does work fine. Was hoping to use the newest version of the library though.
